version: '3.9'

services:
  master:
    image: chrislusf/seaweedfs:dev # use a remote dev image
    ports:
      - 9333:9333
      - 19333:19333
    command: "master -ip=master"
  volume:
    image: chrislusf/seaweedfs:dev # use a remote dev image
    ports:
      - 8080:8080
      - 18080:18080
    command: 'volume -mserver="master:9333" -port=8080 -ip=volume'
    depends_on:
      - master
  filer:
    image: chrislusf/seaweedfs:dev # use a remote dev image
    ports:
      - 8888:8888
      - 18888:18888
    command: 'filer -master="master:9333" -ip.bind=0.0.0.0'
    depends_on:
      - master
      - volume
  s3:
    image: chrislusf/seaweedfs:dev # use a remote dev image
    ports:
      - 8333:8333
    environment:
      # S3 Authentication Configuration
      - S3_ACCESS_KEY=seaweedfs_access_key_123
      - S3_SECRET_KEY=seaweedfs_secret_key_456
      - S3_REGION=us-east-1
      # Enable authentication for S3 API
      - WEED_S3_AUTH_ENABLED=true
    volumes:
      - ./s3_config.json:/etc/seaweedfs/s3.json
    command: 's3 -filer="filer:8888" -ip.bind=0.0.0.0 -config=/etc/seaweedfs/s3.json'
    depends_on:
      - master
      - volume
      - filer
  webdav:
    image: chrislusf/seaweedfs:dev # use a remote dev image
    ports:
      - 7333:7333
    command: 'webdav -filer="filer:8888"'
    depends_on:
      - master
      - volume
      - filer

# Optional: Add volumes for persistent data
volumes:
  seaweedfs-master-data:
  seaweedfs-volume-data:
  seaweedfs-filer-data: